### ISSUE TITLE
this program how to work?

### ISSUE THREAD

**Issue by ChloePike** [YinBuLiao/STEAM-AUTO-LOGIN#1]
I want to know how it works

**Comment by YinBuLiao** [comment]
Please read readme.md

**Comment by ChloePike** [comment]
> Please read readme.md

The README does not explain how it works, it looks like it moves the "ssnf" file to the working directory of steam? And it comes with a function to download files from HTTP.

**Comment by ChloePike** [comment]
> Please read readme.md

Hope you can explain in detail the working principle of this program in the README🙏🙏🙏

**Comment by YinBuLiao** [comment]
It is to download the ssfn file from the Internet and put it in the steam directory

**Comment by ChloePike** [comment]
> It is to download the ssfn file from the Internet and put it in the steam directory

okkk tk u😀

**Comment by YinBuLiao** [comment]
If you think it's good, you can give me a star

**Comment by ChloePike** [comment]
> If you think it's good, you can give me a star

Try to optimize the code
